language: java

before_install:
# Install dot executable for diagrams
 - "sudo apt-get install graphviz"

script: mvn site

after_success:
 - if [ "$TRAVIS_REPO_SLUG" == "rquinio/asciidoctor-maven-demo" ] && [ ${TRAVIS_PULL_REQUEST} = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then
   deploy.sh
   fi
